### ISSUE TITLE
As a menu creator, I want to be able to create categories and associated items for a category

### ISSUE THREAD

**Issue by tbd-develop** [tbd-friends/paas#2]

**Comment by tbd-develop** [comment]
We hard coded the menu items in the software, but now we want to be able to produce an actual menu. As a creator, I should be able to configure the items and categories along with prices and descriptions.

**Comment by Junicus** [comment]
when we create a category should we require it to be at least in one menu? should we also require it to have at least one item?, or do we create the main fields and later we can say I want to link this set of entities for category to item, or menu to category.

I'm currently leaning to have the requirements, even if it creates some interesting flows, thoughts?

**Comment by tbd-develop** [comment]
#5 Encompasses this, and it makes it too complicated to track multiple stories
