### ISSUE TITLE
Store the menu when creating in the menu-management system

### ISSUE THREAD

**Issue by tbd-develop** [tbd-friends/paas#5]
Needs to be done before #2 and should store in independent mongo database

**Comment by tbd-develop** [comment]
- [ ] Store menu independently of what is published

- [ ] Create coordinating identifier that is safe to publish

**Comment by Junicus** [comment]
where should we store it? I'm thinking in sql server, the are relations in the data, but on the other hand, it's also like a document, so mongodb will also be a good fit.

What would be the way to go?

**Comment by Junicus** [comment]
When creating and managing the menus, we could have a state Published/Unpublished to help distinguish menus that are valid and visible vs. menus that are being worked on.

#7 #8 #17

**Comment by tbd-develop** [comment]
- Add features to UI to support. 
- Commands;
-- CreateCategory
-- CreateItem
-- AssociateItemWithCategory
-- AssociateCategoryWithMenu 

Should store items and categories in SQL db, should associate items and categories with menu
