### ISSUE TITLE
Should we add a webapi project for the menu service?

### ISSUE THREAD

**Issue by Junicus** [tbd-friends/paas#6]
Currently we have the blazor app as  a website for that service, should we create a webapi project to separate the ui from the service itself?  or do we add the api controllers in the same project?

How about a class library for holding the commands and queries on it's own so the logic lives in a contained project?

**Comment by tbd-develop** [comment]
If we intend (i.e. what do you want to see?) to manage the menu through one system, breaking out an API only serves to keep us agnostic of UI which if we break things out in to command/query handlers is easily achievable later. Thoughts?

**Comment by Junicus** [comment]
ok, we create the commands / queries first and expose api endpoints later if another service needs to talk directly to the menu service.

And for now we only expose menus using kafka?

**Comment by tbd-develop** [comment]
We can revisit this question at a later point
